# Generated by Django 3.2.15 on 2024-03-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарии к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('cooking', 'Заказ готовится'), ('delivery', 'Заказ доставляется'), ('closed', 'Заказ завершен')], db_index=True, default='new', max_length=15, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default=True, verbose_name='Место доставки'),
        ),
    ]
