# Generated by Django 3.2.15 on 2024-03-28 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0003_auto_20240326_2039"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="create_at",
        ),
        migrations.AddField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата звонка"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата доставки"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="registered_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
